import type { Metadata } from "next";
import "./globals.css";
import { funnel, space, share, fira } from "@/lib/fonts";
import { KeyPressProvider } from "@/components/KeyPressContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnel.variable} ${space.variable} ${share.variable} ${fira.variable} antialiased`}
      >
        <KeyPressProvider>
          {children}
        </KeyPressProvider>
      </body>
    </html>
  );
}
